### ISSUE TITLE
Need to use this with ESPHome

### ISSUE THREAD

**Issue by Arise** [GroundStudio/GroundStudio_Carbon_S2#2]
What should I use under esp32 > board in the yaml file? 

example:
```
# Example configuration entry
esp32:
  board: nodemcu-32s
  framework:
    type: arduino
    version: 2.0.0
```
